#!/bin/bash

## Location of Pandoc support files.
PREFIX=../lib

## Pandoc options to use for all document types
##OPTIONS = markdown+simple_tables+table_captions+yaml_metadata_block+smart
OPTIONS=markdown+simple_tables+table_captions+yaml_metadata_block


### RUN STUFF
rm -f *.pdf *.png *.md *.html
R --slave -e "knitr::knit(input='datapunkt.Rmd',output='datapunkt.md')"
pandoc -r $OPTIONS -w html  --template=$PREFIX/templates/html/html-github.template --css=$PREFIX/css/kultiad.css --self-contained -o datapunkt.html datapunkt.md


